[package]
name = "rsa"
version = "0.1.0"
authors = ["endit"]
edition = "2018"


[dependencies]
num-primes = "0.1.1"
rand = "0.6"
num-bigint = {version = "0.2", features = ["rand"]}
base64 = "0.13.0"
num-traits = "0.2.14"